server:
  port: 8081
devguide:
  message: "디폴트 1234"
---
spring: 
  profiles: dev
server:
  port: 8091 
devguide:
  message: "개발"  
---
spring: 
  profiles: live
server:
  port: 81
devguide:
  message: "운영"  
