server:
  port: 9222
devguide:
  message: "디폴트 2"
---
spring: 
  profiles: dev
server:
  port: 9090 
devguide:
  message: "개발"  
---
spring: 
  profiles: live
server:
  port: 9080   
devguide:
  message: "운영"  
