server:
  port: 8222
devguide:
  message: "디폴트 2"
---
spring: 
  profiles: dev
server:
  port: 8090 
devguide:
  message: "개발"  
---
spring: 
  profiles: live
server:
  port: 8080   
devguide:
  message: "운영"  
